blank_issues_enabled: true

# contact_links:
#   - name: Microsoft Security Response Center ğŸ”
#     url: julien.caillon@gmail.com
#     about: Please report security vulnerabilities to this email address.
